# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('qdpc_core_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamictable',
            name='product_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='qdpc_core_models.productbatchs'),
        ),
        migrations.AddField(
            model_name='dynamictablerow',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='product.dynamictable'),
        ),
    ]
