# Generated by Django 5.2.5 on 2025-08-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('section', models.CharField(choices=[('Pages', 'Pages'), ('Product Data Management', 'Product Data Management'), ('Miscellaneous Data Management', 'Miscellaneous Data Management'), ('User Management', 'User Management'), ('Report Generation', 'Report Generation'), ('Roles Management', 'Roles Management')], max_length=50)),
                ('page_id', models.IntegerField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['page_id'],
            },
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_url', models.CharField(max_length=200)),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Page Permission',
                'verbose_name_plural': 'Page Permissions',
                'unique_together': {('group', 'page_name', 'permission_type')},
            },
        ),
    ]
