# Generated by Django 4.2 on 2025-09-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepermission',
            name='permission_type',
            field=models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20),
        ),
    ]
