# Generated by Django 5.1 on 2024-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='acceptance_test',
            field=models.ManyToManyField(blank=True, null=True, related_name='raw_materials', to='qdpc_core_models.acceptancetest'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='precertified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
