# Generated by Django 4.2 on 2025-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='calibration_validity_duration_type',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], max_length=6),
        ),
    ]
