# Generated by Django 4.2 on 2025-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0002_update_process_step_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='process_type',
            field=models.CharField(choices=[('quantitative', 'Quantitative'), ('qualitative', 'Qualitative')], default='quantitative', max_length=15),
        ),
        migrations.AlterField(
            model_name='rawmaterialacceptancetest',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='raw_material_acceptance_tests/'),
        ),
    ]
