# Generated by Django 5.1 on 2024-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0002_alter_rawmaterial_acceptance_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='user_defined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterialdocument',
            name='raw_material',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
