# Generated by Django 5.1 on 2024-11-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0003_alter_rawmaterial_user_defined_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='user_defined_date',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
