# Generated by Django 5.2.5 on 2025-08-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0003_alter_processstep_process_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatchs',
            name='qa_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbatchs',
            name='qa_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_product_batches_s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbatchs',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productbatchs',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending QA'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], default='pending', max_length=20),
        ),
    ]
