# Generated by Django 5.2.5 on 2025-08-26 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0004_productbatchs_qa_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatchs',
            name='submitted_by_role',
            field=models.CharField(blank=True, help_text='Role of the user who submitted this batch for approval', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productbatchs',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_product_batches_s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbatchs',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
