# Generated by Django 5.1 on 2024-11-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0004_alter_rawmaterial_user_defined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptancetest',
            name='color',
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='test_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
