# Generated by Django 5.1 on 2024-12-09 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0004_alter_rawmaterial_user_defined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptancetest',
            name='color',
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='test_result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='shelf_life_type',
            field=models.CharField(blank=True, choices=[('tbd', 'TBD (To Be Decided)'), ('not_applicable', 'Not Applicable'), ('add_duration', 'Add Duration')], default='tbd', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acceptancetest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qdpc_core_models.unit'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='rm_status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Material Expired', 'Material Expired')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='shelf_life_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='shelf_life_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='user_defined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
