# Generated by Django 4.2 on 2025-08-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0005_productbatchs_submitted_by_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatchs',
            name='approval_remarks',
            field=models.TextField(blank=True, help_text='Remarks/comments when approving the batch', null=True),
        ),
    ]
