# Generated by Django 4.2 on 2025-08-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0006_productbatchs_approval_remarks'),
        ('qdpc_core_models', '0006_update_notification_model'),
    ]

    operations = [
    ]
