# Generated by Django 5.2.5 on 2025-08-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0003_update_acceptance_test_field_lengths'),
        ('qdpc_core_models', '0006_update_notification_model'),
    ]

    operations = [
    ]
