# Generated by Django 4.2 on 2025-08-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0007_merge_20250831_0112'),
        ('qdpc_core_models', '0007_merge_20250831_0956'),
    ]

    operations = [
    ]
