# Generated by Django 4.2 on 2025-08-31 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0008_merge_20250831_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.CreateModel(
            name='QARReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(default='VSSC/QPDC/QAR/Product-A/2024/Rec: 2451', max_length=100)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('introduction', models.TextField(blank=True, help_text='Brief introduction about the product and purpose of this report', null=True)),
                ('scope', models.TextField(blank=True, help_text='Scope of the quality assessment', null=True)),
                ('batch_summary', models.TextField(blank=True, help_text='Summary of the batches/units covered in this report', null=True)),
                ('end_use', models.TextField(blank=True, help_text='End use description', null=True)),
                ('processing_agency', models.TextField(blank=True, help_text='Processing agency details', null=True)),
                ('process_changes', models.TextField(blank=True, help_text='Summary of any changes in process, materials, or specifications', null=True)),
                ('impact_assessment', models.TextField(blank=True, help_text='Impact assessment of changes', null=True)),
                ('raw_materials_qa', models.TextField(blank=True, help_text='QA observations and remarks for raw materials', null=True)),
                ('components_qa', models.TextField(blank=True, help_text='QA observations and remarks for components', null=True)),
                ('in_process_qa', models.TextField(blank=True, help_text='QA observations and remarks for in-process checks', null=True)),
                ('inspections_qa', models.TextField(blank=True, help_text='QA observations and remarks for inspections', null=True)),
                ('test_results', models.TextField(blank=True, help_text='Summary of test results and findings', null=True)),
                ('quality_assurance', models.TextField(blank=True, help_text='Quality assurance observations and recommendations', null=True)),
                ('conclusion', models.TextField(blank=True, help_text='Overall conclusion and recommendations', null=True)),
                ('additional_remarks', models.TextField(blank=True, help_text='Any additional remarks or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_qar_reports', to=settings.AUTH_USER_MODEL)),
                ('product_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qar_reports', to='qdpc_core_models.productbatchs')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_qar_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QAR Report',
                'verbose_name_plural': 'QAR Reports',
                'ordering': ['-created_at'],
                'unique_together': {('product_batch', 'report_number')},
            },
        ),
    ]
