# Generated by Django 4.2 on 2025-08-31 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qdpc_core_models', '0009_alter_notification_options_qarreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarreport',
            name='division_head',
            field=models.ForeignKey(blank=True, help_text='Division Head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_head_qar_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qarreport',
            name='engineer',
            field=models.ForeignKey(blank=True, help_text='Engineer responsible for the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_qar_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qarreport',
            name='section_head',
            field=models.ForeignKey(blank=True, help_text='Section Head', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_head_qar_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
